service: exampleCrud-sls
frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
functions:
  - ${file(src/index.yml)}
resources:
  - ${file(src/user/table.yml)}
